Add missing definition of _NEON2SSE_ALIGN_32 for gcc / clang
Fixes:
```
contrib/libs/arm_neon_2_x86_sse/NEON_2_SSE.h:467:1: error: unknown type name '_NEON2SSE_ALIGN_32'
_NEON2SSE_ALIGN_32 static const int8_t mask8_16_even_odd[32]
```